### ISSUE TITLE
Can't add to compendium folder (Bug)

### ISSUE THREAD

**Issue by Jonwh25** [earlSt1/vtt-compendium-folders#57] opened 2021-03-25 03:09 UTC
![image](https://user-images.githubusercontent.com/60674327/112412793-531c7600-8cdc-11eb-8f51-a8b8c704db71.png)

Getting the error when I try to create a folder and create a new compendium. It basically won't even let me click ok to add the compendiums to the folder.

I am running 0.7.9 with DND 1.2.4.

I uninstalled and reinstalled the module. I even wiped out my folder config and started from scratch but no matter what I can't do it. This is with your latest release.  The old version didn't have any problems.

The only thing I can think is that some of my compendiums have characters in them that might be causing it.

For example. One of my compendiums is named  Journals of that guy (You know - that guy)

So maybe it is a ()'s or - issue with the characters.

**Comment by earlSt1** [comment] 2021-03-25 07:09
Hi, that looks a bit strange. I've just pushed a quick update to the testing branch which may fix this issue. Could you test by uninstalling your current version and installing using the manifest below?

https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

**Comment by Jonwh25** [comment] 2021-03-25 18:54
That seems to have fixed it.

**Comment by Jonwh25** [comment] 2021-03-25 18:58
Although now... it looks like I have stuff sitting in the "Default" folder and when I go to try to assign them, it says there is nothing under "Unassigned". They show up in the main section. If the folder is a subfolder and I update it, it moves the subfolder out of the folder and places it at the top level. Strange behavior but it is working at least and I can just drag the folder to where it needs to go (which is kinda cool)

**Comment by Jonwh25** [comment] 2021-03-25 19:08
Yeah. Even if I update a subfolders color, it pulls it out to the top level. Not a big deal, I can drag it back under the folder I want. At least it is all working (even if not working as intended).

**Comment by earlSt1** [comment] 2021-03-25 20:24
Good to hear, yeah i've had a few issues in the past while testing the edit dialog and folders. I need to do some more i think.

As for the default folder, that is weird. It should definitely be unassigned. I'll play around on my test machine see if i can replicate it.

My first thought was these issues could have arisen from using the previous broken version, but if its still happening then that cant be the case. At least it sort of works for now while i can fix the other stuff.

**Comment by earlSt1** [comment] 2021-03-28 10:23
Can you reinstall again using the above manifest? I think ive just fixed those 2 issues you mentioned (Default folder showing as assigned and subfolders moving to top level)

**Comment by Jonwh25** [comment] 2021-03-28 21:15
> Can you reinstall again using the above manifest? I think ive just fixed those 2 issues you mentioned (Default folder showing as assigned and subfolders moving to top level)

Tested out.  Looks like it is all working correctly now. Thank you.

**Comment by SirBigoo** [comment] 2021-04-02 08:37
Hello,

Same here but that lead to a foundry broken world. If I uninstall module, it cames back to normal otherwise it infinite loading at startup (looks like an infinite loop somewhere).

I suppose this bugs come after those steps : 
1. Create a folder `f1`
2. Create another folder `f2`
3. Move second folder in first (move `f1` to `f2`)
4. Rename root folder (`f1` became `f11`)
5. Try renaming second folder created (c'ant rename `f2`)

When doing this kind of thing, I can't rename the folder (I have this error in console). If I move my `f2` to another folder or at root, name is updated to the one I wanted to set.
After playing around with this bug, I restart foundry and... Infinite loader :D

**Comment by earlSt1** [comment] 2021-04-02 08:54
That sounds bad, could you send me your Export Configuration? I've tried to reproduce these steps but it's working ok for me with the test version.

Also which system + foundry version?

**Comment by SirBigoo** [comment] 2021-04-02 09:15
I did a lot of move / rename... Pretty hard to know what I exactly done, but it was only folder organization :( 

How can I retrieve this configuration please ?
**_System :_** dd5e
**_Foundry :_** latest, 0.7.9

**Comment by SirBigoo** [comment] 2021-04-02 09:16
> That sounds bad, could you send me your Export Configuration? I've tried to reproduce these steps but it's working ok for me with the test version.
> 
> Also which system + foundry version?

I did a lot of move / rename... Pretty hard to know what I exactly done, but it was only folder organization :( 

How can I retrieve this configuration please ?
**_System :_** dd5e
**_Foundry :_** latest, 0.7.9

**Comment by earlSt1** [comment] 2021-04-02 09:17
In the module settings, there should be an Import/Export configuration option.

**Comment by SirBigoo** [comment] 2021-04-02 09:23
> In the module settings, there should be an Import/Export configuration option.

Did not have that option either on world & on startup screen.
Do you want to have all my installed modules ? If yes I can find this kind of options with another module (tidyui)

**Comment by earlSt1** [comment] 2021-04-02 09:27
I doubt its another module interfering, I suspect what's happened is after dragging/moving stuff around a bunch, the logic in my module has tripped up somewhere, causing there to be some infinite loop.

Another option is if you have a public facing server, to setup a temporary GM account for me to connect and debug on your machine.

**Comment by SirBigoo** [comment] 2021-04-02 09:59
> I doubt its another module interfering, I suspect what's happened is after dragging/moving stuff around a bunch, the logic in my module has tripped up somewhere, causing there to be some infinite loop.
> 
> Another option is if you have a public facing server, to setup a temporary GM account for me to connect and debug on your server.

I use local setup but I can temporary expose this server on internet for debugging purposes. I prefer that you contact me in private to grant you those access.

**Comment by earlSt1** [comment] 2021-04-02 10:01
Sure no problem, completely understandable. If you have discord you can shoot me a message (@Erceron#0370). I'm not sure if github has a private messaging system.

**Comment by earlSt1** [comment] 2021-04-03 15:37
Fixed in v2.2.2 (both issues in this chain hopefully)

**Comment by SirBigoo** [comment] 2021-04-05 08:03
Just tried with my broken game in 2.2.2, still infinite loading.
Is there something I have to do in order to fix it back ?

**Comment by earlSt1** [comment] 2021-04-05 09:31
Moved the issue @SirBigoo was experiencing into new issue (#64)

**Closed by earlSt1** 2021-04-05 09:31 UTC
Labels: bug
